CREATE TABLE IF NOT EXISTS `ROLE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

INSERT INTO `ROLE` (`ID`, `NAME`) VALUES
	(1, 'ROLE_ADMIN'),
	(2, 'ROLE_MEMBER'),
	(3, 'ROLE_SUPER_MEMBER'),
	(4, 'ROLE_OWNER');



	CREATE TABLE IF NOT EXISTS `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTIVE` bit(1) DEFAULT NULL,
  `DATE_OF_BIRTH` date DEFAULT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `FIRST_NAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `SETTINGS_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USER_EMAIL` (`EMAIL`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;



CREATE TABLE `USER_SETTINGS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`USER_ID` INT NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

ALTER TABLE `USER_SETTINGS` ADD CONSTRAINT `FK_USER_SETTINGS_USER_ID` FOREIGN KEY (USER_ID) REFERENCES USER(ID);
ALTER TABLE `USER` ADD CONSTRAINT `FK_USER_USER_SETTINGS` FOREIGN KEY (SETTINGS_ID) REFERENCES USER_SETTINGS(ID);


CREATE TABLE IF NOT EXISTS `USER_ROLES` (
  `USER_ID` int(11) NOT NULL,
  `ROLE_ID` int(11) NOT NULL,
  PRIMARY KEY (`USER_ID`,`ROLE_ID`),
  KEY `FK_USER_ROLES_KEY` (`ROLE_ID`),
  CONSTRAINT `FK_USER_ROLES_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),
  CONSTRAINT `FK_USER_ROLES_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `USER_MEMBERS` (
  `USER_ID` int(11) NOT NULL,
  `MEMBER_ID` int(11) NOT NULL,
  PRIMARY KEY (`USER_ID`,`MEMBER_ID`),
  CONSTRAINT `FK_USER_MEMBERS_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),
  CONSTRAINT `FK_USER_MEMBERS_MEMBER` FOREIGN KEY (`MEMBER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
