CREATE TABLE `CURRENCY` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `NAME` varchar(255) NOT NULL,
    `CURRENCY` varchar(255) NOT NULL,
    `SHORT_NAME` varchar(255) NOT NULL,
    `CURR_CROSS_RATE` float DEFAULT 1 NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_CURRENCY` (`NAME`,`SHORT_NAME`)
);


CREATE TABLE `USER_CURRENCY` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `CURRENCY` int NOT NULL,
    `CROSS_RATE` FLOAT DEFAULT 1 NOT NULL,
    `OWNER` int  NOT NULL,
    `DEF` bit(1) DEFAULT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_CURRENCY_USER_DEF` (`OWNER`,`CURRENCY`)
);
ALTER TABLE `USER_CURRENCY` ADD CONSTRAINT `FK_USER_CURENCY_CURR` FOREIGN KEY (CURRENCY) REFERENCES CURRENCY(ID);
ALTER TABLE `USER_CURRENCY` ADD CONSTRAINT `FK_USER_CURENCY_OWNER` FOREIGN KEY (OWNER) REFERENCES USER(ID);

CREATE TABLE `USER_CURRENCY_RATE` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `CURRENCY` int NOT NULL,
    `DATE` TIMESTAMP NOT NULL,
    `RATE` FLOAT NOT NULL,
    PRIMARY KEY (`ID`)
);

ALTER TABLE `USER_CURRENCY_RATE` ADD CONSTRAINT `FK_USER_CURENCY_RATE` FOREIGN KEY (CURRENCY) REFERENCES USER_CURRENCY(ID);
