CREATE TABLE `OPERATION` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `ACTIVE` bit(1) DEFAULT NULL,
    `DATE` DATE NOT NULL,
    `OWNER` int not null,
    `ACCOUNT` int not null,
    `CATEGORY` int not null,
    `CURRENCY` int not null,
    `CURRENCY_CROSS_RATE` int NOT NULL,
    `MONEY`  float  NOT NULL,
    `NOTE` varchar(2000) not null,
    PRIMARY KEY (`ID`)
);

ALTER TABLE `OPERATION` ADD CONSTRAINT `FK_OPER_USER` FOREIGN KEY (OWNER) REFERENCES USER(ID);
ALTER TABLE `OPERATION` ADD CONSTRAINT `FK_OPER_CATEGORY` FOREIGN KEY (CATEGORY) REFERENCES USER_CATEGORY(ID);
ALTER TABLE `OPERATION` ADD CONSTRAINT `FK_OPER_CURRENCY` FOREIGN KEY (CURRENCY) REFERENCES USER_CURRENCY(ID);
ALTER TABLE `OPERATION` ADD CONSTRAINT `FK_OPER_ACCOUNT` FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNT(ID);
ALTER TABLE `OPERATION` ADD CONSTRAINT `FK_OPER_CROSS` FOREIGN KEY (CURRENCY_CROSS_RATE) REFERENCES USER_CURRENCY_RATE(ID);

CREATE TABLE `EXCHANGE` (
    `OPERATION_ID` int(11) not null,
    `ACCOUNT_TO` int not null,
    `CURRENCY_TO` int not null,
    `CURRENCY_CROSS_RATE_TO` int NOT NULL,
    `MONEY_TO`  float  NOT NULL
);

ALTER TABLE `EXCHANGE` ADD CONSTRAINT `FK_EXCHANGE_CURRENCY` FOREIGN KEY (CURRENCY_TO) REFERENCES USER_CURRENCY(ID);
ALTER TABLE `EXCHANGE` ADD CONSTRAINT `FK_EXCHANGE_ACCOUNT` FOREIGN KEY (ACCOUNT_TO) REFERENCES ACCOUNT(ID);
ALTER TABLE `EXCHANGE` ADD CONSTRAINT `FK_EXCHANGE_CROSS` FOREIGN KEY (CURRENCY_CROSS_RATE_TO) REFERENCES USER_CURRENCY_RATE(ID);
