CREATE TABLE `BUDGET` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `ACTIVE` bit(1) DEFAULT NULL,
    `DATE_FROM` DATE NOT NULL,
    `DATE_TO` DATE NOT NULL,
    `OWNER` int not null,
    `NAME` varchar(255) not null,
    PRIMARY KEY (`ID`)
);
ALTER TABLE `BUDGET` ADD CONSTRAINT `FK_BUDGET_USER` FOREIGN KEY (OWNER) REFERENCES USER(ID);

CREATE TABLE `BUDGET_LINE` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `ACTIVE` bit(1) DEFAULT NULL,
    `CATEGORY` int not null,
    `BUDGET` int not null,
    `MONEY` float not null,
    PRIMARY KEY (`ID`)
);

ALTER TABLE `BUDGET_LINE` ADD CONSTRAINT `FK_BLINE_BUDGET` FOREIGN KEY (BUDGET) REFERENCES BUDGET(ID);
ALTER TABLE `BUDGET_LINE` ADD CONSTRAINT `FK_BLINE_CATEG` FOREIGN KEY (CATEGORY) REFERENCES USER_CATEGORY(ID);